import type { QueryInterface, Op } from 'sequelize';

const DROPDOWN_VALUES = [
  {
    name: 'January',
    type: 'months',
    sequence: 1,
    fromDate: new Date('2026-01-01'),
    toDate: new Date('2026-01-31'),
    fromMonthNum: 1,
    toMonthNum: 1,
  },
  {
    name: 'February',
    type: 'months',
    sequence: 2,
    fromDate: new Date('2026-02-01'),
    toDate: new Date('2026-02-29'),
    fromMonthNum: 2,
    toMonthNum: 2,
  },
  {
    name: 'March',
    type: 'months',
    sequence: 3,
    fromDate: new Date('2026-03-01'),
    toDate: new Date('2026-03-31'),
    fromMonthNum: 3,
    toMonthNum: 3,
  },
  {
    name: 'April',
    type: 'months',
    sequence: 4,
    fromDate: new Date('2026-04-01'),
    toDate: new Date('2026-04-30'),
    fromMonthNum: 4,
    toMonthNum: 4,
  },
  {
    name: 'May',
    type: 'months',
    sequence: 5,
    fromDate: new Date('2026-05-01'),
    toDate: new Date('2026-05-31'),
    fromMonthNum: 5,
    toMonthNum: 5,
  },
  {
    name: 'June',
    type: 'months',
    sequence: 6,
    fromDate: new Date('2026-06-01'),
    toDate: new Date('2026-06-30'),
    fromMonthNum: 6,
    toMonthNum: 6,
  },
  {
    name: 'July',
    type: 'months',
    sequence: 7,
    fromDate: new Date('2026-07-01'),
    toDate: new Date('2026-07-31'),
    fromMonthNum: 7,
    toMonthNum: 7,
  },
  {
    name: 'August',
    type: 'months',
    sequence: 8,
    fromDate: new Date('2026-08-01'),
    toDate: new Date('2026-08-31'),
    fromMonthNum: 8,
    toMonthNum: 8,
  },
  {
    name: 'September',
    type: 'months',
    sequence: 9,
    fromDate: new Date('2026-09-01'),
    toDate: new Date('2026-09-30'),
    fromMonthNum: 9,
    toMonthNum: 9,
  },
  {
    name: 'October',
    type: 'months',
    sequence: 10,
    fromDate: new Date('2026-10-01'),
    toDate: new Date('2026-10-31'),
    fromMonthNum: 10,
    toMonthNum: 10,
  },
  {
    name: 'November',
    type: 'months',
    sequence: 11,
    fromDate: new Date('2026-11-01'),
    toDate: new Date('2026-11-30'),
    fromMonthNum: 11,
    toMonthNum: 11,
  },
  {
    name: 'December',
    type: 'months',
    sequence: 12,
    fromDate: new Date('2026-12-01'),
    toDate: new Date('2026-12-31'),
    fromMonthNum: 12,
    toMonthNum: 12,
  },
  {
    name: '1st Quarter',
    type: 'months',
    sequence: 13,
    fromDate: new Date('2026-01-01'),
    toDate: new Date('2026-03-31'),
    fromMonthNum: 1,
    toMonthNum: 3,
  },
  {
    name: '2nd Quarter',
    type: 'months',
    sequence: 14,
    fromDate: new Date('2026-04-01'),
    toDate: new Date('2026-06-30'),
    fromMonthNum: 4,
    toMonthNum: 6,
  },
  {
    name: '3rd Quarter',
    type: 'months',
    sequence: 15,
    fromDate: new Date('2026-07-01'),
    toDate: new Date('2026-09-30'),
    fromMonthNum: 7,
    toMonthNum: 9,
  },
  {
    name: '4th Quarter',
    type: 'months',
    sequence: 16,
    fromDate: new Date('2026-10-01'),
    toDate: new Date('2026-12-31'),
    fromMonthNum: 10,
    toMonthNum: 12,
  },
  {
    name: 'Half Yearly',
    type: 'months',
    sequence: 17,
    fromDate: new Date('2026-01-01'),
    toDate: new Date('2026-06-30'),
    fromMonthNum: 1,
    toMonthNum: 6,
  },
  {
    name: 'Yearly',
    type: 'months',
    sequence: 18,
    fromDate: new Date('2026-01-01'),
    toDate: new Date('2026-12-31'),
    fromMonthNum: 1,
    toMonthNum: 12,
  },
  {
    name: '2026',
    type: 'years',
    sequence: 1,
    fromDate: new Date('2026-01-01'),
    toDate: new Date('2026-12-31'),
    fromMonthNum: null,
    toMonthNum: null,
  },
  {
    name: '2027',
    type: 'years',
    sequence: 2,
    fromDate: new Date('2027-01-01'),
    toDate: new Date('2027-12-31'),
    fromMonthNum: null,
    toMonthNum: null,
  },
  {
    name: '2028',
    type: 'years',
    sequence: 3,
    fromDate: new Date('2028-01-01'),
    toDate: new Date('2028-12-31'),
    fromMonthNum: null,
    toMonthNum: null,
  },
  {
    name: '2029',
    type: 'years',
    sequence: 4,
    fromDate: new Date('2029-01-01'),
    toDate: new Date('2029-12-31'),
    fromMonthNum: null,
    toMonthNum: null,
  },
  {
    name: '2030',
    type: 'years',
    sequence: 5,
    fromDate: new Date('2030-01-01'),
    toDate: new Date('2030-12-31'),
    fromMonthNum: null,
    toMonthNum: null,
  },
];

export async function up(queryInterface: QueryInterface) {
  const now = new Date();

  await queryInterface.bulkInsert(
    'Dropdowns',
    DROPDOWN_VALUES.map((obj) => ({
      name: obj.name,
      type: obj.type,
      sequence: obj.sequence,
      fromDate: obj.fromDate,
      toDate: obj.toDate,
      fromMonthNum: obj.fromMonthNum,
      toMonthNum: obj.toMonthNum,
      createdAt: now,
      updatedAt: now,
    })),
    {}
  );
}

export async function down(queryInterface: QueryInterface) {
  await queryInterface.bulkDelete(
    'Dropdowns',
    {
      name: { [Op.in]: DROPDOWN_VALUES.map((obj) => obj.name) as string[] },
      type: { [Op.in]: DROPDOWN_VALUES.map((obj) => obj.type) as string[] },
    },
    {}
  );
}
