import { Request, Response } from 'express';
import bcrypt from 'bcrypt';
import models from '../../models/index';
import { Op } from 'sequelize';

const signup = async (req: Request, res: Response): Promise<void> => {
  try {
    const {
      email,
      password,
      name,
      middleName,
      surName,
      mobileNumber,
      countryCode,
      dob,
      tob,
      TypeId,
      GenderId,
    } = req.body;

    // Validate required fields
    if (!email || !password || !name || !mobileNumber || !countryCode || !dob) {
      res.status(400).json({
        success: false,
        msg: 'Missing required fields: email, password, name, mobileNumber, countryCode, and dob are required',
      });
      return;
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      res.status(400).json({
        success: false,
        msg: 'Invalid email format',
      });
      return;
    }

    // Validate password strength (minimum 6 characters)
    if (password.length < 6) {
      res.status(400).json({
        success: false,
        msg: 'Password must be at least 6 characters long',
      });
      return;
    }

    // Validate mobile number (must be numeric and positive)
    const mobileNum = parseInt(mobileNumber, 10);
    if (isNaN(mobileNum) || mobileNum <= 0) {
      res.status(400).json({
        success: false,
        msg: 'Mobile number must be a valid positive number',
      });
      return;
    }

    // Validate country code format (should be 1-4 characters, typically +XX format)
    const countryCodeRegex = /^\+?[1-9]\d{0,3}$/;
    if (!countryCodeRegex.test(countryCode)) {
      res.status(400).json({
        success: false,
        msg: 'Invalid country code format',
      });
      return;
    }

    // Validate date of birth (must be a valid date and in the past)
    const dobDate = new Date(dob);
    if (isNaN(dobDate.getTime())) {
      res.status(400).json({
        success: false,
        msg: 'Invalid date of birth format',
      });
      return;
    }
    if (dobDate >= new Date()) {
      res.status(400).json({
        success: false,
        msg: 'Date of birth must be in the past',
      });
      return;
    }

    // Validate time of birth format (if provided) - HH:MM:SS or HH:MM
    if (tob) {
      const timeRegex = /^([0-1][0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$/;
      if (!timeRegex.test(tob)) {
        res.status(400).json({
          success: false,
          msg: 'Invalid time of birth format. Use HH:MM or HH:MM:SS format',
        });
        return;
      }
    }

    // Validate TypeId if provided
    if (TypeId) {
      const typeIdNum = parseInt(TypeId, 10);
      if (isNaN(typeIdNum) || typeIdNum <= 0) {
        res.status(400).json({
          success: false,
          msg: 'TypeId must be a valid positive number',
        });
        return;
      }
      const typeExists = await models.TypeMasters.findByPk(typeIdNum);
      if (!typeExists) {
        res.status(400).json({
          success: false,
          msg: 'Invalid TypeId. The specified type does not exist',
        });
        return;
      }
    }

    // Validate GenderId if provided
    if (GenderId) {
      const genderIdNum = parseInt(GenderId, 10);
      if (isNaN(genderIdNum) || genderIdNum <= 0) {
        res.status(400).json({
          success: false,
          msg: 'GenderId must be a valid positive number',
        });
        return;
      }
      const genderExists = await models.GenderMasters.findByPk(genderIdNum);
      if (!genderExists) {
        res.status(400).json({
          success: false,
          msg: 'Invalid GenderId. The specified gender does not exist',
        });
        return;
      }
    }

    // Check if user with this email already exists
    const existingUser = await models.Users.findOne({
      where: { email: {[Op.iLike]: email} },
    });

    if (existingUser) {
      res.status(409).json({
        success: false,
        msg: 'User with this email already exists',
      });
      return;
    }

    // Hash password
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash(password, saltRounds);

    // Create new user
    // uid will be auto-generated by the database sequence (users_uid_seq)
    // Using type assertion because uid has a database default value
    const newUser = await models.Users.create({
      email: email.trim(),
      password: hashedPassword,
      name: name.trim(),
      middleName: middleName ? middleName.trim() : null,
      surName: surName ? surName.trim() : null,
      mobileNumber: mobileNum,
      countryCode: countryCode.trim(),
      dob: dobDate,
      tob: tob || null,
      TypeId: TypeId ? parseInt(TypeId, 10) : null,
      GenderId: GenderId ? parseInt(GenderId, 10) : null,
      isActive: true,
      isVerified: false,
    } as any);

    // Return success response (exclude password from response)
    const userResponse = {
      id: newUser.id,
      uid: newUser.uid,
      email: newUser.email,
      name: newUser.name,
      middleName: newUser.middleName,
      surName: newUser.surName,
      mobileNumber: newUser.mobileNumber,
      countryCode: newUser.countryCode,
      dob: newUser.dob,
      tob: newUser.tob,
      isActive: newUser.isActive,
      isVerified: newUser.isVerified,
      TypeId: newUser.TypeId,
      GenderId: newUser.GenderId,
      createdAt: newUser.createdAt,
      updatedAt: newUser.updatedAt,
    };

    res.status(201).json({
      success: true,
      msg: 'User signed up successfully',
      data: userResponse,
    });
  } catch (err: any) {
    console.error('Signup error:', err);

    // Handle Sequelize validation errors
    if (err.name === 'SequelizeValidationError') {
      res.status(400).json({
        success: false,
        msg: 'Validation error',
        errors: err.errors.map((e: any) => e.message),
      });
      return;
    }

    // Handle unique constraint violations
    if (err.name === 'SequelizeUniqueConstraintError') {
      res.status(409).json({
        success: false,
        msg: 'A user with this email or uid already exists',
      });
      return;
    }

    // Generic error response
    res.status(500).json({
      success: false,
      msg: 'Something went wrong, we are looking into it',
    });
  }
};

export { signup };